 
// THIS FILE IS GENERATED BY A SCRIPT, CHANGES WILL NOT PERSIST. EDIT THE CORRESPONDING .in TEMPLATE FILE INSTEAD.

using namespace System;
using namespace System::Reflection;
using namespace System::Runtime::CompilerServices;
using namespace System::Runtime::InteropServices;
using namespace System::Security::Permissions;

#ifdef _DEBUG
[assembly:AssemblyTitleAttribute(L"WASimClient [DBG]")];
[assembly:AssemblyConfigurationAttribute("Debug")]
#else
[assembly:AssemblyTitleAttribute(L"WASimClient")];
[assembly:AssemblyConfigurationAttribute("Release")]
#endif

[assembly:AssemblyDescriptionAttribute(L"CLI Wrapper for WASimCommander's general API and the WASimClient class.")];
[assembly:AssemblyCompanyAttribute(L"Maxim Paperno")];
[assembly:AssemblyProductAttribute(L"WASimCommander - Remote access to the Microsoft Flight Simulator 2020 Gauge API.")];
[assembly:AssemblyCopyrightAttribute(L"Copyright Maxim Paperno; All rights reserved.")];
[assembly:AssemblyTrademarkAttribute(L"")];
[assembly:AssemblyCultureAttribute(L"")];

[assembly:AssemblyVersionAttribute(L"1.0.0.6")];
[assembly:AssemblyFileVersionAttribute("1.0.0.6")];
[assembly:AssemblyInformationalVersionAttribute("1.0.0.6-beta2")];

[assembly:ComVisible(false)];
