/*
This file is part of the WASimCommander project.
https://github.com/mpaperno/WASimCommander

COPYRIGHT: (c) Maxim Paperno; All Rights Reserved.

This file may be used under the terms of either the GNU General Public License (GPL)
or the GNU Lesser General Public License (LGPL), as published by the Free Software
Foundation, either version 3 of the Licenses, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

Copies of the GNU GPL and LGPL are included with this project
and are available at <http://www.gnu.org/licenses/>.
*/

// THIS FILE IS GENERATED BY A SCRIPT, CHANGES WILL NOT PERSIST. EDIT THE CORRESPONDING .in TEMPLATE FILE INSTEAD.

#pragma once

#define WSMCMND_PROJECT_NAME      "WASimCommander"
#define WSMCMND_CLIENT_NAME       "WASimClient"
#define WSMCMND_SERVER_NAME       "WASimModule"
#define WSMCMND_GUI_NAME          "WASimUI"

#define WSMCMND_VER_MAJOR         1
#define WSMCMND_VER_MINOR         3
#define WSMCMND_VER_PATCH         1
#define WSMCMND_VER_BUILD         0
// Git commit hash (top 8 bytes)
#define WSMCMND_VER_COMIT         0x36E925C4UL
/// Version number in 32 bit "binary coded decimal", eg. 0x01230400 = 1.23.4.0
#define WSMCMND_VERSION           0x01030100UL
/// Possible version suffix, eg "-beta1"  (can be blank for release versions)
#define WSMCMND_VER_NAME          ""
/// Dotted version string Maj.Min.Pat.Bld, eg. "1.23.4.0"
#define WSMCMND_VERSION_STR       "1.3.1.0"
/// Dotted version string with possible suffix, eg. "1.23.4.0-beta1"
#define WSMCMND_VERSION_INFO      "1.3.1.0"
/// Build date & time in ISO-8601 "Zulu Time" format, UTC
#define WSMCMND_BUILD_DATE        "2024-11-28T15:16:43Z"


#define WSMCMND_PROJECT_URL       "https://github.com/mpaperno/WASimCommander"
#define WSMCMND_PROJECT_COPYRIGHT "Copyright Maxim Paperno; All rights reserved."
#define WSMCMND_PROJECT_DESCRIPT  "Remote access to the Microsoft Flight Simulator 2020 Gauge API."
#define WSMCMND_PROJECT_LICENSE   "WASimCommander API and WASimClient licensed under LGPL v3 or GPL v3. WASimModule and all other code licensed under GPL v3. Full terms are detailed in the README, LICENSE.GPL.txt, and LICENSE.LGPL.txt files which should accompany this distribution and are available at the project's URL."
